bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update] do
    member do
        get :following, :followers
      end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get 'search' => 'search#search'
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :following_relationships,foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following
  has_many :follower_relationships,foreign_key: "following_id",class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  # current_user.following?(@user) <= @user = User.find(2)
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
    # self.followings.include?(other_user)
    # current_user.following_relationships.find_by(following_id: @user.id)
  end

  def follow(other_user)
    following_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  
  def self.search(search, word)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @user = User.where(name: word)
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  
  # app/models/user.rb に追記
  include JpPrefecture
  jp_prefecture :prefecture_code  # prefecture_codeはuserが持っているカラム

  # postal_codeからprefecture_nameに変換するメソッドを用意します．
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction,
    length: { maximum: 50 }
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user  = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end


  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    # binding.pry
    # @book = Book.find(params[:id])
    @new = Book.new
    @book_comment = BookComment.new
    @books = @user.books
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    # @book = Book.find(params[:id])
    @new = Book.new
    @book_comment = BookComment.new
    @books = @user.books
    render 'show_follower'
  end



  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, )
  end

end

bookers2/app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
     user == current_user
  end

end

bookers2/app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

bookers2/app/views/users/_follow_form.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user: user %>
  <% else %>
    <%= render 'follow', user: user %>
  <% end %>
<% end %>

bookers2/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2/app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback:'no_image.jpg' %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

<%= render 'users/stats', user: @user, users: @users %>
<%= render 'users/follow_form', user: @user, users: @users %>

bookers2/app/views/users/_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  </a>
</div>

bookers2/app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

bookers2/app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

bookers2/app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= render 'users/profile', user: @user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>
  </div>

  <div class="col-xs-9">
    <h2>Users</h2>
    <!--users一覧 -->
    <table class="table">
  	    <thead>
	  	    <tr>
			    <th>image</th>
			    <th>name</th>
		  	    <th colspan="3"></th>
		    </tr>
	    </thead>

	    <tbody>
		    <% @users.each do |user| %>
		    <tr>
			    <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			    <td><%= user.name %></td>
			    <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			    <td><%= render 'users/stats', user: user %></td>
			    <td><%= render 'users/follow_form', user: user %></td>
		    </tr>
		    <% end %>
	    </tbody>
    </table>
    <!--users一覧 -->
  </div>
</div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book, user: @book.user %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td><%= book.book_comments.count %>件コメント</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>
</div>

bookers2/app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
	  	<%= render 'users/profile', user: @user %>
  		<h2>New book</h2>
	  	<%= render 'books/form', book: @new %>
    </div>

    <div class="col-xs-9">
      <h2>Followings</h2>
      <% @user.followings.each do |user| %>
        <table class="table">
          <thead>
	  	      <tr>
			        <th>image</th>
			        <th>name</th>
		  	      <th colspan="3"></th>
		        </tr>
	        </thead>
	        <tbody>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
              <td>  <%= user.name %> </td>
              <td><%= link_to 'Show', user_path(user) %></td>
              <td><%= render 'users/stats', user: user %></td>
			        <td><%= render 'users/follow_form', user: user %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/show_follower.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
  		<%= render 'users/profile', user: @user %>

	  	<h2>New book</h2>
	  	<%= render 'books/form', book: @new %>
    </div>

    <div class="col-xs-9">
      <h2>Followers</h2>
      <% @user.followers.each do |user| %>
      <table class="table">
        <thead>
	  	    <tr>
			      <th>image</th>
			      <th>name</th>
		  	    <th colspan="3"></th>
		    </tr>
	      </thead>
	      <tbody>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
            <td><%= render 'users/stats', user: user %></td>
	  		    <td><%= render 'users/follow_form', user: user %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>